### ISSUE TITLE
updateParticipantData API not working - IHCS data items not updated

### ISSUE THREAD

**Issue by dbakumar** [episphere/connectFaas#12]
As part of Wife used Husband PIN scenario, we need to update the studyId and other data items  belongs to Wife for that token even though API returns "Success" Message but data not updated properly. 

example
Husband token : "1108baf1-3787-4aad-ab3d-61736a899477"
Husband State :     "state":       {
         "477091792": "512786135",
         "481139103": "456806539",
         "667474224": "834544960",
         "706256705": "178420302",
         "749475364": "V1.0_12162020",
         "849518448": "768826601",
         "934298480": "363147933",
         "uid": "DKfLhhjMg3XHVKagukI2e9Ck6fF3",
         "studyId": "HP20210310241600"
      }
 
Needs to Update for Wife as below : 

{
	"data": {
		"706256705": "536341288",
		"934298480": "636706443",
		"849518448": "178420302",
		"749475364": "V1.0_12162020VIJAY",
		"477091792": "582670006",
		"481139103": "",
		"667474224": "",
		"token": "1108baf1-3787-4aad-ab3d-61736a899477",
		"studyId": "HP20210310266927"
	}
}

updateParticipantData API response as below : 
 {
   "message": "Success!",
   "code": 200
}

**Comment by bhaumik55231** [comment]
If we want to update the state attributes it needs to be enclosed within a ```state``` object as shown below ;-

```
{
	"data": {
        "token": "1108baf1-3787-4aad-ab3d-61736a899477",
        "471168198": "William",
        "state": {
            "706256705": "536341288",
            "934298480": "636706443",
            "849518448": "178420302",
            "749475364": "V1.0_12162020VIJAY",
            "477091792": "582670006",
            "481139103": "",
            "667474224": "",
            "studyId": "HP20210310266927"
        }
    }
}
```
