### ISSUE TITLE
consistencyCheck API fails to enforce consistency rules 

### ISSUE THREAD

**Issue by nrandorf** [episphere/connectFaas#243]
The consistencyCheck API will return a successful call for datatypes outside of the stated consistency rules. For instance, the consistencyCheck will return a successful response for both string and integer values.

**Comment by anthonypetersen** [comment]
@nrandorf can you please provide an example of a payload you sent to this API that returned unexpected results?

**Comment by nrandorf** [comment]
Sure, below is an example payload you can test. Note that all values in the key-value pairs in this example are empty strings.  The consistency check should fail if the values are strings, regardless of the string length.   Example payload:  {"data": [{'token': ‘your-fake-token-here’, '821247024': '', '444699761': '', '953614051': '', '793822265': '', '147176963': '', '557461333': '', '725929722': '', '711794630': '', '679832994': '', '570452130': '', '629484663': '', '547895941': '', '188797763': ''}]}

**Comment by anthonypetersen** [comment]
@nrandorf are you guys reading the JSON contents of the response?

**Comment by nrandorf** [comment]
Hi Tony, we read the json response and specifically examine the status code. An example is below.   Were you able to replicate the error?  
Example: 
response = consistencyresponse.json()
response["code"]

**Comment by anthonypetersen** [comment]
This is what my data looks like initialized:

![image](https://user-images.githubusercontent.com/18222069/190017717-e60ef51f-42a5-4db3-997c-9ccdf5918e97.png)


This is what my function looks like that I threw together:

![image](https://user-images.githubusercontent.com/18222069/190017814-9547d2b0-20b2-4752-9c74-792897dc4773.png)

**Comment by nrandorf** [comment]
Hi @anthonypetersen, thanks for this detailed example!  Below is what I see in our API test.  I know what's happening now.  I still see that the consistencyCheck API returns a successful status code for data types outside the state consistency rules, but understand we should reference the code inside the json body 
<img width="613" alt="ConsistencyTest" src="https://user-images.githubusercontent.com/73665548/190216673-db9db85f-561d-43b1-b145-90f81ff38a0e.png">
instead. This was a misunderstanding on my part.

**Comment by anthonypetersen** [comment]
@nrandorf that makes sense... We can probably do a better job of highlighting that in our documentation. I think the point of view it was written from was the call technically worked, so return a 200 status, but you need to look inside the JSON object for the status of the call itself.

It seems like we got this resolved so I'm going to close this, let me know if you need anything else from me though.

**Comment by nrandorf** [comment]
@anthonypetersen, It might be more intuitive if request result status code and error code matched, but I see the other point of the view as well.  A documentation highlight might help others from making the same mistake.  I appreciate the assistance.
