### ISSUE TITLE
Provider Error Message When Receiving Invalid Responses (Concept IDs)

### ISSUE THREAD

**Issue by eibergenr** [episphere/connectFaas#89]
We inadvertently used old concept IDs.  When we sent through the updates for the participants, everything seemed to process correctly.  In looking at the Site Study Dashboard it also showed "other" so we thought things had worked.  Unfortunately, we had not used valid concept ids.  Could a message be sent back to the sender notifying that there is a invalid concept id.  Perhaps not stop the message from going through but at least provide notification that there is something that needs to be reviewed.  Rob Strenn on our team would be a good person to discuss this with if interested in learning more.  Thanks!

**Comment by anthonypetersen** [comment]
This should be handled now through updates to updateParticipantData logic
